language: dart

dart:
# Install a specific stable release
- '1.24.2'

branches:
  only:
  - toh-test-travis

install_dartium: true
xvfb: false

script: pub run angular_test

dart_task:

 # Warnings are fatal, but we only analyze the lib/ directory.
 - dartanalyzer: --fatal-warnings lib/ --ignore-unrecognized-flags --no-hints --options=analysis_options.yaml
 - dartfmt

