language: dart

matrix:
  include:
    - dart: '1.24.2'
  fast_finish: false

branches:
  only:
  - toh-test-travis

cache:
  apt: true
  directories:
    - $HOME/.pub-cache

install:
  - travis_retry pub get

script:
  - pub run angular_test

dart_task:
  install_dartium: true
  xvfb: false
