language: dart

dart:
# Install a specific stable release
- '>=1.24.2 <2.0.0'

branches:
  only:
  - toh-test-travis

dart_task:
 - angular_test

 install_dartium: true

 # Warnings are fatal, but we only analyze the lib/ directory.
 - dartanalyzer: --fatal-warnings lib/ --ignore-unrecognized-flags --no-hints --options=analysis_options.yaml
 - dartfmt