language: dart

matrix:
  include:
    - dart: '1.24.2'
    - dart: stable
    - dart: dev
  allow_failures:
    - dart: dev
  fast_finish: true

branches:
  only:
  - toh-test-travis

install_dartium: true
xvfb: false

cache:
  apt: true
  directories:
    - $HOME/.pub-cache

install:
  - travis_retry pub get

script:
#  - pub run grinder analyze lint
  - pub run angular_test

dart_task:

 # Warnings are fatal, but we only analyze the lib/ directory.
  - dartanalyzer: --fatal-warnings lib/ --ignore-unrecognized-flags --no-hints --options=analysis_options.yaml
  - dartfmt
