analyzer:
  strong-mode: true
#   exclude:
#     - path/to/excluded/files/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
# Style Rules
    - always_specify_types

# Pub Rules
    - package_names
