name: angular_tour_of_heroes
description: Tutorial App for AngularDart
version: 0.0.1

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  angular2: ^3.1.0
  dart_style: ^1.0.6
  http: "^0.11.3+14"
  stream_transform: ^0.0.8

dev_dependencies:
  angular_test: 1.0.0-beta+3
  browser: ^0.10.0+2
  dart_to_js_script_rewriter: ^1.0.3
  grinder: ^0.8.0
  mockito: ^2.0.2
  test: ^0.12.24
  tuneup: ^0.3.1

transformers:
- angular2:
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
- angular2/transform/reflection_remover:
    $include: test/**_test.dart

- test/pub_serve:
    $include: test/**_test.dart

- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
