name: angular_tour_of_heroes
description: Tutorial App for AngularDart
version: 0.0.1

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_router: ^1.0.2
  dart_style: ^1.0.6
  http: "^0.11.3+14"
  stream_transform: ^0.0.8

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0+2
  dart_to_js_script_rewriter: ^1.0.3
  mockito: ^2.0.2
  test: ^0.12.24

transformers:
- angular:
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'

# Run the code generator on the entire package.
- angular/transform/codegen

- angular/transform/reflection_remover:
    $include: test/**_test.dart

- test/pub_serve:
    $include: test/**_test.dart

- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
